apiVersion: v1
kind: Pod
metadata:
  name: ny-taxi-driver
  namespace: emr-data-team-a
spec:
  volumes:
    # This is using the temp storage on the node.
    # if you are using NVMe SSD then karpenter will configure the RAID0 under /mnt/k8s-disks/0 and copies the shuffle data to this location
    - name: spark-local-dir-1
      emptyDir: {}

  nodeSelector:
    NodeGroupType: "SparkMemoryOptimized"
    karpenter.sh/capacity-type: "on-demand"
    topology.kubernetes.io/zone: "us-west-2b"


  containers:
    - name: spark-kubernetes-driver # Don't change this name. EMR on EKS looking for this name
      volumeMounts:
        - name: spark-local-dir-1
          mountPath: /data1
          readOnly: false

  tolerations:
    - key: "spark-memory-optimized"
      operator: "Exists"
      effect: "NoSchedule"
