stages:
  - env-creation
  - prepare-${{values.awsEnvironmentName}}-stage

variables:
  APP_SHORT_NAME: "${{ values.component_id }}"
  APP_TEMPLATE_NAME: "example-generic"
  GLENT_PLATFORM_REGION: "${{ values.platformRegion }}"

include:
  - project: 'glent-admin/backstage-reference'
    ref: main 
    file:
      - 'common/cicd/.gitlab-ci-job-defaults-cdk.yml'
      - 'common/cicd/.gitlab-ci-aws-base.yml'
      - 'common/cicd/.gitlab-ci-aws-iac-s3.yml'
