apiVersion: v1
kind: Pod
metadata:
  name: ny-taxi-driver
  namespace: emr-data-team-a
  labels:
    applicationId: ny-taxi-yunikorn
    queue: root.test
  annotations:
    yunikorn.apache.org/schedulingPolicyParameters: "placeholderTimeoutSeconds=30 gangSchedulingStyle=Hard"
    yunikorn.apache.org/task-group-name: "spark-driver"
    # YuniKorn Gang Scheduling Configuration
    # minMember should match with driver and executor instances
    # minResource cpu and memory should match with driver and executor cpu and memory. This includes sidecar container resources.
    # Resource below should never be less than the actual resources defined for Driver and Executor with sidecar containers
    yunikorn.apache.org/task-groups: |-
      [{
          "name": "spark-driver",
          "minMember": 1,
          "minResource": {
            "cpu": "1200m",
            "memory": "15Gi"
          },
          "nodeSelector": {
            "NodeGroupType": "SparkMemoryOptimized"
          },
          "tolerations": [{"key" : "spark-memory-optimized", "operator": "Exists", "effect": "NoSchedule"}]
        },
        {
          "name": "spark-executor",
          "minMember": 20,
          "minResource": {
            "cpu": "1200m",
            "memory": "15Gi"
          },
          "nodeSelector": {
            "NodeGroupType": "SparkMemoryOptimized"
          },
          "tolerations": [{"key" : "spark-memory-optimized", "operator": "Exists", "effect": "NoSchedule"}]
      }]
spec:
  volumes:
    # This is using the temp storage on the node.
    # if you are using NVMe SSD then karpenter will configure the RAID0 under /mnt/k8s-disks/0 and copies the shuffle data to this location
    - name: spark-local-dir-1
      emptyDir: {}

  nodeSelector:
    NodeGroupType: "SparkMemoryOptimized"
    karpenter.sh/capacity-type: "on-demand"
    topology.kubernetes.io/zone: "us-west-2b"

  containers:
    - name: spark-kubernetes-driver # Don't change this name. EMR on EKS looking for this name
      volumeMounts:
        - name: spark-local-dir-1
          mountPath: /data1
          readOnly: false

  tolerations:
    - key: "spark-memory-optimized"
      operator: "Exists"
      effect: "NoSchedule"
