apiVersion: v1
kind: Pod
metadata:
  name: ny-taxi-exec
  namespace: emr-data-team-a
  labels:
    applicationId: ny-taxi-yunikorn
    queue: root.test # YuniKorn Queue
  annotations:
    yunikorn.apache.org/task-group-name: "spark-executor" # YuniKorn Gang Scheduling annotation

spec:
  volumes:
    # This is using the temp storage on the node.
    # if you are using NVMe SSD then karpenter will configure the RAID0 under /mnt/k8s-disks/0 and copies the shuffle data to this location
    - name: spark-local-dir-1
      emptyDir: {}

  nodeSelector:
    NodeGroupType: "SparkMemoryOptimized"
    topology.kubernetes.io/zone: "us-west-2b"

  containers:
    - name: spark-kubernetes-executor # Don't change this name. EMR on EKS looking for this name
      volumeMounts:
        - name: spark-local-dir-1
          mountPath: /data1
          readOnly: false

  tolerations:
    - key: "spark-memory-optimized"
      operator: "Exists"
      effect: "NoSchedule"
