name: website-deploy-to-github-pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'website/**'
      - '.github/workflows/website-deploy.yml'
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./website
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: --cwd ./website install
      - name: Build website
        uses: borales/actions-yarn@v4
        with:
          cmd: --cwd ./website build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.API_GITHUB_TOKEN }}
          publish_dir: ./website/build
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
